In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import category_encoders as ce
from sklearn import preprocessing
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.utils import np_utils

In [2]:
df = pd.read_csv('Bank_Customers.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.drop(['CustomerId' , 'Surname' , 'RowNumber'] , axis=1 , inplace=True)

In [5]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [6]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [7]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [8]:
onehot = ce.OneHotEncoder(cols='Geography').fit(X)
X = onehot.transform(X)

In [9]:
label = preprocessing.LabelEncoder()

X['Gender']= label.fit_transform(X['Gender'])

In [10]:
X

,CreditScore,Geography_1,Geography_2,Geography_3,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,1,0,0,0,42,2,0.00,1,1,1,101348.88
1,608,0,1,0,0,41,1,83807.86,1,0,1,112542.58
2,502,1,0,0,0,42,8,159660.80,3,1,0,113931.57
3,699,1,0,0,0,39,1,0.00,2,0,0,93826.63
4,850,0,1,0,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,0,0,1,39,5,0.00,2,1,0,96270.64
9996,516,1,0,0,1,35,10,57369.61,1,1,1,101699.77
9997,709,1,0,0,0,36,7,0.00,1,0,1,42085.58
9998,772,0,0,1,1,42,3,75075.31,2,1,0,92888.52
9999,792,1,0,0,0,28,4,130142.79,1,1,0,38190.78

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.1 )

In [12]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
ann = Sequential()

In [26]:
ann.add(Dense(units=256 , activation='relu'))
ann.add(Dense(units=256 , activation='relu'))
ann.add(Dense(units=1 , activation='sigmoid'))

In [27]:
ann.compile(optimizer='Adam' , loss='binary_crossentropy' , metrics=['accuracy'] , )

In [28]:
ann.fit(X_train , y_train , batch_size=32 , epochs=150 ,shuffle=True )

Epoch 1/150
282/282 [==============================] - 1s 1ms/step - loss: 0.4009 - accuracy: 0.8294
Epoch 2/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3486 - accuracy: 0.8582
Epoch 3/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3410 - accuracy: 0.8587
Epoch 4/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3362 - accuracy: 0.8606
Epoch 5/150
282/282 [==============================] - 0s 948us/step - loss: 0.3325 - accuracy: 0.8618
Epoch 6/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3273 - accuracy: 0.8652
Epoch 7/150
282/282 [==============================] - 0s 900us/step - loss: 0.3241 - accuracy: 0.8660
Epoch 8/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3196 - accuracy: 0.8689
Epoch 9/150
282/282 [==============================] - 0s 944us/step - loss: 0.3172 - accuracy: 0.8687
Epoch 10/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3136 - accuracy: 0.8726
Epoch 11/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3114 - accuracy: 0.8716
Epoch 12/150
282/282 [==============================] - 0s 1ms/step - loss: 0.3074 - accuracy: 0.8712
Epoch 13/150
282/282 [==============================] - 0s 970us/step - loss: 0.3017 - accuracy: 0.8763
Epoch 14/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2982 - accuracy: 0.8764
Epoch 15/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2957 - accuracy: 0.8777
Epoch 16/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2934 - accuracy: 0.8789
Epoch 17/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2877 - accuracy: 0.8777
Epoch 18/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2841 - accuracy: 0.8818
Epoch 19/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2798 - accuracy: 0.8843
Epoch 20/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2752 - accuracy: 0.8856
Epoch 21/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2700 - accuracy: 0.8846
Epoch 22/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2680 - accuracy: 0.8882
Epoch 23/150
282/282 [==============================] - 0s 947us/step - loss: 0.2632 - accuracy: 0.8883
Epoch 24/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2609 - accuracy: 0.8923
Epoch 25/150
282/282 [==============================] - 0s 987us/step - loss: 0.2558 - accuracy: 0.8936
Epoch 26/150
282/282 [==============================] - 0s 970us/step - loss: 0.2516 - accuracy: 0.8971
Epoch 27/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2474 - accuracy: 0.8987
Epoch 28/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2449 - accuracy: 0.8953
Epoch 29/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2393 - accuracy: 0.9017
Epoch 30/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2366 - accuracy: 0.9026
Epoch 31/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2326 - accuracy: 0.9013
Epoch 32/150
282/282 [==============================] - 0s 957us/step - loss: 0.2266 - accuracy: 0.9064
Epoch 33/150
282/282 [==============================] - 0s 974us/step - loss: 0.2264 - accuracy: 0.9058
Epoch 34/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2189 - accuracy: 0.9087
Epoch 35/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2165 - accuracy: 0.9111
Epoch 36/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2108 - accuracy: 0.9108
Epoch 37/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2055 - accuracy: 0.9118
Epoch 38/150
282/282 [==============================] - 0s 1ms/step - loss: 0.2026 - accuracy: 0.9146
Epoch 39/150
282/282 [==============================] - 0s 978us/step - loss: 0.1993 - accuracy: 0.9150
Epoch 40/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1946 - accuracy: 0.9198
Epoch 41/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1888 - accuracy: 0.9222
Epoch 42/150
282/282 [==============================] - 0s 934us/step - loss: 0.1858 - accuracy: 0.9217
Epoch 43/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1830 - accuracy: 0.9236
Epoch 44/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1791 - accuracy: 0.9262
Epoch 45/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1776 - accuracy: 0.9250
Epoch 46/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1710 - accuracy: 0.9290
Epoch 47/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1662 - accuracy: 0.9327
Epoch 48/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1646 - accuracy: 0.9308
Epoch 49/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1596 - accuracy: 0.9357
Epoch 50/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1598 - accuracy: 0.9337
Epoch 51/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1529 - accuracy: 0.9368
Epoch 52/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1495 - accuracy: 0.9401
Epoch 53/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1457 - accuracy: 0.9429
Epoch 54/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1396 - accuracy: 0.9431
Epoch 55/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1364 - accuracy: 0.9437
Epoch 56/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1362 - accuracy: 0.9450
Epoch 57/150
282/282 [==============================] - 0s 958us/step - loss: 0.1326 - accuracy: 0.9457
Epoch 58/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1253 - accuracy: 0.9500
Epoch 59/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1279 - accuracy: 0.9476
Epoch 60/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1237 - accuracy: 0.9506
Epoch 61/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1205 - accuracy: 0.9488
Epoch 62/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1160 - accuracy: 0.9547
Epoch 63/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1138 - accuracy: 0.9536
Epoch 64/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1129 - accuracy: 0.9523
Epoch 65/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1103 - accuracy: 0.9558
Epoch 66/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1098 - accuracy: 0.9584
Epoch 67/150
282/282 [==============================] - 0s 1ms/step - loss: 0.1049 - accuracy: 0.9592
Epoch 68/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0987 - accuracy: 0.9620
Epoch 69/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0956 - accuracy: 0.9637
Epoch 70/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0959 - accuracy: 0.9663
Epoch 71/150
282/282 [==============================] - 0s 927us/step - loss: 0.0905 - accuracy: 0.9649
Epoch 72/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0892 - accuracy: 0.9648
Epoch 73/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0853 - accuracy: 0.9698
Epoch 74/150
282/282 [==============================] - 0s 901us/step - loss: 0.0898 - accuracy: 0.9640
Epoch 75/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0826 - accuracy: 0.9709
Epoch 76/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0828 - accuracy: 0.9703
Epoch 77/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0804 - accuracy: 0.9722
Epoch 78/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0798 - accuracy: 0.9694
Epoch 79/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0783 - accuracy: 0.9722
Epoch 80/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0726 - accuracy: 0.9729
Epoch 81/150

282/282 [==============================] - 0s 1ms/step - loss: 0.0784 - accuracy: 0.9706
Epoch 82/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0686 - accuracy: 0.9771
Epoch 83/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0686 - accuracy: 0.9738
Epoch 84/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0694 - accuracy: 0.9761
Epoch 85/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0641 - accuracy: 0.9783
Epoch 86/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0712 - accuracy: 0.9752
Epoch 87/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0654 - accuracy: 0.9758
Epoch 88/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0647 - accuracy: 0.9798
Epoch 89/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0599 - accuracy: 0.9780
Epoch 90/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0568 - accuracy: 0.9811
Epoch 91/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0581 - accuracy: 0.9809
Epoch 92/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0570 - accuracy: 0.9812
Epoch 93/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0617 - accuracy: 0.9779
Epoch 94/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0581 - accuracy: 0.9794
Epoch 95/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0521 - accuracy: 0.9821
Epoch 96/150
282/282 [==============================] - 0s 922us/step - loss: 0.0552 - accuracy: 0.9809
Epoch 97/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0504 - accuracy: 0.9823
Epoch 98/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0522 - accuracy: 0.9828
Epoch 99/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0595 - accuracy: 0.9786
Epoch 100/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0421 - accuracy: 0.9876
Epoch 101/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0523 - accuracy: 0.9838
Epoch 102/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0523 - accuracy: 0.9831
Epoch 103/150
282/282 [==============================] - 0s 908us/step - loss: 0.0545 - accuracy: 0.9814
Epoch 104/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0420 - accuracy: 0.9866
Epoch 105/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0416 - accuracy: 0.9884
Epoch 106/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0389 - accuracy: 0.9877
Epoch 107/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0446 - accuracy: 0.9844
Epoch 108/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0390 - accuracy: 0.9889
Epoch 109/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0431 - accuracy: 0.9842
Epoch 110/150
282/282 [==============================] - 0s 949us/step - loss: 0.0403 - accuracy: 0.9863
Epoch 111/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0510 - accuracy: 0.9839
Epoch 112/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0408 - accuracy: 0.9870
Epoch 113/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0358 - accuracy: 0.9898
Epoch 114/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0482 - accuracy: 0.9839
Epoch 115/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0368 - accuracy: 0.9880
Epoch 116/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0385 - accuracy: 0.9882
Epoch 117/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0458 - accuracy: 0.9854
Epoch 118/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0576 - accuracy: 0.9794
Epoch 119/150
282/282 [==============================] - 0s 952us/step - loss: 0.0389 - accuracy: 0.9869
Epoch 120/150
282/282 [==============================] - 0s 990us/step - loss: 0.0300 - accuracy: 0.9926
Epoch 121/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0471 - accuracy: 0.9834
Epoch 122/150
282/282 [==============================] - 0s 999us/step - loss: 0.0337 - accuracy: 0.9892
Epoch 123/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0279 - accuracy: 0.9928
Epoch 124/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0306 - accuracy: 0.9913
Epoch 125/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0296 - accuracy: 0.9911
Epoch 126/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0344 - accuracy: 0.9889
Epoch 127/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0491 - accuracy: 0.9839
Epoch 128/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0466 - accuracy: 0.9859
Epoch 129/150
282/282 [==============================] - 0s 978us/step - loss: 0.0288 - accuracy: 0.9919
Epoch 130/150
282/282 [==============================] - 0s 998us/step - loss: 0.0284 - accuracy: 0.9917
Epoch 131/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0295 - accuracy: 0.9927
Epoch 132/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0333 - accuracy: 0.9896
Epoch 133/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0253 - accuracy: 0.9927
Epoch 134/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0216 - accuracy: 0.9937
Epoch 135/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0481 - accuracy: 0.9867
Epoch 136/150
282/282 [==============================] - 0s 985us/step - loss: 0.0413 - accuracy: 0.9882
Epoch 137/150
282/282 [==============================] - 0s 948us/step - loss: 0.0282 - accuracy: 0.9926
Epoch 138/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0321 - accuracy: 0.9900
Epoch 139/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0277 - accuracy: 0.9927
Epoch 140/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0236 - accuracy: 0.9941
Epoch 141/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0328 - accuracy: 0.9894
Epoch 142/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0442 - accuracy: 0.9836
Epoch 143/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0361 - accuracy: 0.9879
Epoch 144/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0192 - accuracy: 0.9939
Epoch 145/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0234 - accuracy: 0.9930
Epoch 146/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0303 - accuracy: 0.9909
Epoch 147/150
282/282 [==============================] - 0s 931us/step - loss: 0.0253 - accuracy: 0.9937
Epoch 148/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0327 - accuracy: 0.9906
Epoch 149/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0292 - accuracy: 0.9913
Epoch 150/150
282/282 [==============================] - 0s 1ms/step - loss: 0.0233 - accuracy: 0.9948

In [29]:
ann.predict(sc.transform([[600 , 1 , 0 , 0 ,1 , 40 , 3 , 60000 , 2 , 1 , 1 , 50000]]))

1/1 [==============================] - 0s 24ms/step

array([[0.00284686]], dtype=float32)

## Most likely The Customer will stay with us